This is makeindex, version 2.15 [TeX Live 2012] (kpathsea + Thai support).
Scanning style file ./EAI-Book.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file EAI-Book.acn.....done (1626 entries accepted, 0 rejected).
Sorting entries.................done (20911 comparisons).
Generating output file EAI-Book.acr....done (493 lines written, 0 warnings).
Output written in EAI-Book.acr.
Transcript written in EAI-Book.alg.
